### ISSUE TITLE
Add link to briefcase project in auto-generated README.rst

### ISSUE THREAD

**Issue by samredway** [pybee/briefcase-template#4]
It may be useful to put some kind of link to the briefcase project as a whole in the auto-generated README.rst.

This could be helpful to the user - to have a quick link to the docs - but also acts as free promotion if the link is spread around github a little.

Something as simple as:

"This cross platform app is generated by [briefcase](https://github.com/pybee/briefcase) - visit the site for full documentation."

**Comment by freakboy3742** [comment]
Nice idea! It should be relatively straightforward to implement, too; we just need to update the various project templates:
* [pybee/Python-iOS-template](https://github.com/pybee/Python-iOS-template) 
* [pybee/Python-Android-template](https://github.com/pybee/Python-Android-template) 
* [pybee/Python-macOS-template](https://github.com/pybee/Python-macOS-template) 
* [pybee/Python-Windows-template](https://github.com/pybee/Python-Windows-template) 
* [pybee/Python-Django-template](https://github.com/pybee/Python-Django-template)

**Comment by samredway** [comment]
I'll be happy to go ahead and do this - I'll look at at this week if that's OK? Also if anyone has any input on wording?

**Comment by eliasdorneles** [comment]
Suggestion:

> "This cross platform app is generated by briefcase - a BeeWare project: https://pybee.org/briefcase"

**Comment by freakboy3742** [comment]
Sounds great! 

As for the text:

> This cross-platform app was generated by [Briefcase](https://github.com/pybee/briefcase) - part of [The BeeWare Project](https://pybee.org). If you want to see more tools like Briefcase, please consider [becoming a financial member of BeeWare](https://pybee.org/contributing/membership/).

**Comment by samredway** [comment]
Great - will do.

**Comment by samredway** [comment]
So I put in a PR with the text added to the autogenerated README.rst created for projects generated using the briefcase-template. @freakboy3742 you did mention adding the same text to the other templates - but looking at it (admittedly quite briefly so pls correct me if I'm mixed up) I think that you use the briefcase template to create the top level app - setup.py, application folder and the README.rst - and this README will wind up being at the root level of the github repo. 

This one we now have covered. 

But for the other templates these are actually used by the briefcase app and are created as sub folders which hold particular distributions but do not have a description of the project in. As such I don't think we necessarily want to do add this text there? Or at least not in the same way?

**Comment by freakboy3742** [comment]
@samredway True - I was overthinking it. There isn't much point putting this text in the README for the platform templates. There might be other ways to surface an "advertising" line, though - for example, in a startup splash screen. But that's definitely for another PR :-)
